# Configuration for requeset.sh.

# Patrick Lavallee Delgado
# University of Chicago

# Specify the geography and the name of the table in which to store these data.
geography: tract
table: profile_by_tract
endpoint: https://api.census.gov/data/!!YEAR!!/acs/acs5/profile?

# Map variable identifiers to readable labels by year.
2010: 
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2011:
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2012:
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2013:
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2014:
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2015:
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2016:
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2017:
  DP05_0070E: population
  DP05_0077PE: white
  DP05_0078PE: black
  DP05_0071PE: hispanic
  DP05_0080PE: asian
  DP05_0018E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
