# Configuration for requeset.sh.

# Patrick Lavallee Delgado
# Harris School of Public Policy
# University of Chicago
# February 2020

# Specify the geography and the name of the table in which to store these data.
geography: tract
table: profile_by_tract

# Specify API endpoints and variables by year.
2010: https://api.census.gov/data/2010/acs/acs5/profile?
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2011: https://api.census.gov/data/2011/acs/acs5/profile?
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2012: https://api.census.gov/data/2012/acs/acs5/profile?
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2013: https://api.census.gov/data/2013/acs/acs5/profile?
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2014: https://api.census.gov/data/2014/acs/acs5/profile?
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2015: https://api.census.gov/data/2015/acs/acs5/profile?
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2016: https://api.census.gov/data/2016/acs/acs5/profile?
  DP05_0065E: population
  DP05_0072PE: white
  DP05_0073PE: black
  DP05_0066PE: hispanic
  DP05_0075PE: asian
  DP05_0017E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
2017: https://api.census.gov/data/2017/acs/acs5/profile?
  DP05_0070E: population
  DP05_0077PE: white
  DP05_0078PE: black
  DP05_0071PE: hispanic
  DP05_0080PE: asian
  DP05_0018E: median_age
  DP03_0062E: median_hhinc
  DP02_0067PE: bachelors
  DP02_0081E: moved_in_county
  DP02_0082E: moved_cross_county
  DP02_0084E: moved_cross_state
  DP02_0079E: stayed
  DP04_0050E: housing_units
